Repository pixeldeee/disspy, pull requests merged in 2022-08, with the labels that each got.

#76 Corrections in the docs
  docs/source/first-steps/contributing.rst
  docs/source/first-steps/getting-started.rst
Labels: documentation, good first issue, mistake

#79 34 add thread support
  disspy/__init__.py
  disspy/client.py
  disspy/core.py
  disspy/thread.py
Labels: new feature

#80 Adding logging system
  .gitignore
  disspy/client.py
Labels: new feature

#89 Update DisBot documentation
  docs/source/objects/bot.rst
Labels: documentation, enhancement
